version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: proyecto_sena
      MYSQL_USER: Cristian
      MYSQL_PASSWORD: 0000
      MYSQL_ROOT_PASSWORD: 0000
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  fastapi:
    build: .
    container_name: fastapi-backend-container
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=proyecto_sena
      - DB_USER=Cristian
      - DB_PASSWORD=0000

volumes:
  mysql_data:
